"""initial schema

Revision ID: 5ef89f9d0b81
Revises: 
Create Date: 2026-02-24 21:30:48.906226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef89f9d0b81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migration_paths',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('classification_tier', sa.String(length=50), nullable=False),
    sa.Column('os_family', sa.String(length=100), nullable=True),
    sa.Column('guidance_text', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vme_matrix',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('os_vendor', sa.String(length=100), nullable=False),
    sa.Column('os_family', sa.String(length=100), nullable=False),
    sa.Column('os_versions', sa.String(length=500), nullable=False),
    sa.Column('classification_tier', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vme_matrix')
    op.drop_table('migration_paths')
    # ### end Alembic commands ###
